CREATE SCHEMA Supermercado;
USE Supermercado;

CREATE TABLE IF NOT EXISTS PRODUCTS (id_product INT NOT NULL AUTO_INCREMENT, 
product_name VARCHAR(50) NOT NULL,
product_type VARCHAR(50) NOT NULL,
cost_price DECIMAL NOT NULL,
sale_price DECIMAL NOT NULL,
product_stock INT NOT NULL,
product_brand VARCHAR(50) NOT NULL,
id_supplier INT NOT NULL,
CONSTRAINT PK_PRODUCTS PRIMARY KEY (id_product)
);

CREATE TABLE IF NOT EXISTS CLIENTS (id_client INT NOT NULL AUTO_INCREMENT,
client_name VARCHAR(50) NOT NULL,
client_dni INT NOT NULL,
client_email VARCHAR(50) NOT NULL,
client_phone VARCHAR(50) NOT NULL,
client_address VARCHAR(50) NOT NULL,
id_order INT NOT NULL,
CONSTRAINT PK_CLIENTS PRIMARY KEY (id_client)
);

CREATE TABLE IF NOT EXISTS SUPPLIERS (id_supplier INT NOT NULL AUTO_INCREMENT,
supplier_name VARCHAR(50) NOT NULL,
supplier_cuit INT NOT NULL,
supplier_email VARCHAR(50) NOT NULL,
supplier_phone VARCHAR(50) NOT NULL,
supplier_address VARCHAR(50) NOT NULL,
id_product INT NOT NULL,
CONSTRAINT PK_SUPPLIERS PRIMARY KEY (id_supplier)
);

CREATE TABLE IF NOT EXISTS ORDERS (id_order INT NOT NULL AUTO_INCREMENT,
order_date DATETIME NOT NULL DEFAULT(CURRENT_TIMESTAMP),
order_price DECIMAL NOT NULL,
id_client INT NOT NULL,
id_product INT NOT NULL,
id_store INT NOT NULL,
CONSTRAINT PK_ORDERS PRIMARY KEY (id_order)
);

CREATE TABLE IF NOT EXISTS STORES (id_store INT NOT NULL AUTO_INCREMENT,
store_name VARCHAR(50) NOT NULL,
store_email VARCHAR(50) NOT NULL,
store_phone VARCHAR(50) NOT NULL,
store_address VARCHAR(50) NOT NULL,
id_employee INT NOT NULL,
id_order INT NOT NULL,
CONSTRAINT PK_STORES PRIMARY KEY (id_store)
);

CREATE TABLE IF NOT EXISTS EMPLOYEES (id_employee INT NOT NULL AUTO_INCREMENT,
employee_name VARCHAR(50) NOT NULL,
employee_cuil INT NOT NULL,
employee_email VARCHAR(50) NOT NULL,
employee_phone VARCHAR(50) NOT NULL,
employee_address VARCHAR(50) NOT NULL,
employee_salary DECIMAL NOT NULL,
join_date DATETIME NOT NULL,
end_date DATETIME,
id_store INT NOT NULL,
CONSTRAINT PK_EMPLOYEES PRIMARY KEY (id_employee)
);

ALTER TABLE PRODUCTS 
ADD CONSTRAINT FK_PRODUCTS_SUPPLIERS FOREIGN KEY FK_PRODUCTS_SUPPLIERS (id_supplier)
REFERENCES SUPPLIERS (id_supplier);

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_CLIENTS FOREIGN KEY FK_ORDERS_CLIENTS (id_client)
REFERENCES CLIENTS (id_client),
ADD CONSTRAINT FK_ORDERS_PRODUCTS FOREIGN KEY FK_ORDERS_PRODUCTS (id_product)
REFERENCES PRODUCTS (id_product),
ADD CONSTRAINT FK_ORDERS_STORES FOREIGN KEY FK_ORDERS_STORES (id_store)
REFERENCES STORES (id_store);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT FK_EMPLOYEES_STORES FOREIGN KEY FK_EMPLOYEES_STORES (id_store)
REFERENCES STORES (id_store);
